# ==============================================================================
# MASTER CONFIGURATION
# ==============================================================================
domain:  # "door.yourdomain.com"
docker_host: # "192.168.1.26"

# Global settings for the app and authentication
onedoor:
  token_expiry_days: 30 #default 30
  users:
    - username: #"first_user"
      password_hash: #use makepass.example
    - username: #"second_user" can add more
      password_hash:
  notifications: #bind /vapid to enable notifications no data goes here
    snooze_all: 120 #snooze seconds after any notification sent
    snooze_same: 120 #cooldown for identical notifications

# Door definitions - List order determines extension: 700, 702, 704...
moredoors:
  - id: #"front"
    call_mode: #"sip" - sip, generic, or none. see docs.
    camera: #"rtsp://192.168.1.31:554/frontsubsmall"
    actions:
      - id: #"front_light" - generic id
        label: #"light" - this is button text
        type: #"hook" hook, dtmf, or link
        url: #"http://192.168.1.66/light" - url for hook or link, payload for dtmf 
        icon: #"🔆" - icon on button
      - id: #"front_lock" - remove unused or add more.
        label: #"Unlock"
        type: #"dtmf"
        payload: #"1234"
        icon: #"🔒"
# - id: "side" - camera/door list works like this
#   call_mode:
#   camera:
