services:
  onedoor:
    image: tylerransdell/onedoor:v030 #can use image now
    build: . #can build also
    container_name: onedoor
#    network_mode: host  #no longer needed
    volumes:
      - ./config.yaml:/app/config.yaml:ro #server config
      - ./logs:/var/log/intercom:rw #optional
      - ./keys:/etc/asterisk/keys:rw #persists dtls keys
    environment:
      - JWT_SECRET= #REQUIRED - any string at least 32 chars
#   devices:
#     - /dev/dri:/dev/dri  --- use hardware acceleration if transcoding camera feed
    restart: unless-stopped
    ports:
      - 8099:8099 #onedoor, lan only, point NPM here.
      - 8557:8557/tcp #fast video, default shown. expose to wan
      - 8557:8557/udp #fast video, default shown. expose to wan
      - 10000-10220:10000-10220/udp #fast audio, default shown. expose to wan
      - 5060:5060 #local intercom 105:one2345door, lan only
#     - 5040:5040 #optional asterisk ami for home assistant monitor hass:one2345door, lan only 
#     - 1984:1984 #optional go2rtc console, lan only
