services:
  onedoor:
    image: tylerransdell/onedoor:latest
    container_name: onedoor
    network_mode: host
    volumes:
      - ./config.yaml:/app/config.yaml:ro #server config
      - ./logs:/var/log/intercom:rw #optional
      - ./keys:/etc/asterisk/keys:rw #persists dtls keys
    environment:
      - JWT_SECRET= #REQUIRED - any string at least 32 chars
#   devices:
#     - /dev/dri:/dev/dri  --- use hardware acceleration if transcoding camera feed
    restart: unless-stopped
#   ports:   ----bridge mode not working must use host networking
#     - 8099:8099 #onedoor
#     - 8557:8557/tcp #fast video, default shown. expose to internet
#     - 8557:8557/udp #fast video, default shown. expose to internet
#     - 10000-10220:10000-10220/udp #fast audio, default shown. expose to internet.
#     - 5060:5060 #local intercom
#     - 5040:5040 #asterisk ami for home assistant
#     - 1984:1984 #go2rtc console
