import yaml
import sys
import os
import secrets
import string
import shutil

# --- UTILS ---
def generate_pbx_password(length=12):
    alphabet = string.ascii_lowercase + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def load_yaml(path):
    with open(path, 'r') as f:
        return yaml.safe_load(f)

class CustomDumper(yaml.Dumper):
    def increase_indent(self, flow=False, indentless=False):
        return super(CustomDumper, self).increase_indent(flow, False)

def str_presenter(dumper, data):
    if data.startswith(':'):
        return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='"')
    return dumper.represent_scalar('tag:yaml.org,2002:str', data)

yaml.add_representer(str, str_presenter, Dumper=CustomDumper)

def write_yaml(path, data):
    with open(path, 'w') as f:
        yaml.dump(data, f, Dumper=CustomDumper, default_flow_style=False, indent=2, sort_keys=False)

# --- PATHS ---
MASTER_CONFIG = '/app/config.yaml'
GO2RTC_SRC = '/app/go2rtc.yaml'
GO2RTC_DEST = '/config/go2rtc.yaml'
ONEDOOR_DEST = '/app/onedoor.yaml'
PBX_DEFAULTS = '/app/pbx_defaults'
ASTERISK_DIR = '/etc/asterisk'

# 1. INITIAL LOAD
master = load_yaml(MASTER_CONFIG)
domain = master.get('domain')
docker_host = master.get('docker_host') # 192.168.1.26

if not domain or not docker_host:
    print("❌ FATAL: Top-level 'domain' and 'docker_host' are required.")
    sys.exit(1)

onedoor_simple = master.get('onedoor', {}).get('simple_mode', False)
go2rtc_simple = master.get('go2rtc', {}).get('simple_mode', False)

# 2. GO2RTC PARSING
if go2rtc_simple:
    print("🔧 Provisioning go2rtc...")
    g_config = load_yaml(GO2RTC_SRC)
    cam_url = master['go2rtc'].get('camera')

    g_config['streams'] = {'camera1': [cam_url]}
    g_config['webrtc'] = {
        'listen': ':8557',
        'candidates': [f"{domain}:8557"],
        'ice_lite': False
    }
    g_config['rtsp'] = {'backchannel': True}
    write_yaml(GO2RTC_DEST, g_config)

# 3. ONEDOOR & PBX PARSING
if onedoor_simple:
    print("🔧 Provisioning OneDoor & Asterisk (Full Overwrite)...")

    # A. Generate Users
    final_users_list = []
    users_input = master['onedoor'].get('users', [])
    for i, u in enumerate([u for u in users_input if u.get('username')]):
        pbx_user = f"user{i+1}"
        pbx_pass = generate_pbx_password()
        final_users_list.append({
            'username': u['username'],
            'password_hash': u['password_hash'],
            'pbx_username': pbx_user,
            'pbx_password': pbx_pass
        })

    # B. Write OneDoor Config
    onedoor_out = {
        'server': {'listen_port': 8099, 'token_expiry_days': master['onedoor'].get('token_expiry_days') or 30},
        'video': {'webrtc_name': 'camera1'},
        'pbx': {'dial_extension': '700', 'user_agent': 'OneDoor - Client'},
        'users': final_users_list,
        'actions': master['onedoor'].get('actions', [])
    }
    write_yaml(ONEDOOR_DEST, onedoor_out)

    # C. ASTERISK OPERATIONS: Copy defaults first
    print(f"🔧 Copying base configs from {PBX_DEFAULTS} to {ASTERISK_DIR}...")
    if not os.path.exists(ASTERISK_DIR):
        os.makedirs(ASTERISK_DIR)

    if os.path.exists(PBX_DEFAULTS):
        for item in os.listdir(PBX_DEFAULTS):
            s = os.path.join(PBX_DEFAULTS, item)
            d = os.path.join(ASTERISK_DIR, item)
            if os.path.isdir(s):
                if item != 'keys': # Protect keys directory
                    if os.path.exists(d): shutil.rmtree(d)
                    shutil.copytree(s, d)
            else:
                shutil.copy2(s, d)
    else:
        print("⚠️ Warning: pbx_defaults directory not found.")

    # D. Build pjsip.conf from scratch
    pjsip_content = f"""; --- AUTO-GENERATED BY ONEDOOR ---
[global]
type=global
user_agent=OneDoor-Intercom
default_realm=asterisk
endpoint_identifier_order=username,ip

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address={docker_host}
external_media_address={docker_host}

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088
external_signaling_address={domain}
external_media_address={domain}

; --- AIPHONE STATION ---
[105]
type=endpoint
context=intercom-logic
disallow=all
allow=ulaw
auth=105_auth
aors=105
transport=transport-udp
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
from_domain={docker_host}

[105_auth]
type=auth
auth_type=userpass
username=105
password=one2345door

[105]
type=aor
max_contacts=1
"""

    # Add WebRTC Endpoints
    for u in final_users_list:
        pjsip_content += f"""
; --- WebRTC User: {u['username']} ---
[{u['pbx_username']}]
type=aor
max_contacts=5
remove_existing=yes

[{u['pbx_username']}-auth]
type=auth
auth_type=userpass
username={u['pbx_username']}
password={u['pbx_password']}
realm=asterisk

[{u['pbx_username']}]
type=endpoint
context=intercom-logic
disallow=all
allow=ulaw
auth={u['pbx_username']}-auth
aors={u['pbx_username']}
transport=transport-ws
webrtc=yes
media_encryption=dtls
dtls_verify=no
dtls_setup=actpass
dtls_cert_file={ASTERISK_DIR}/keys/asterisk.crt
dtls_private_key={ASTERISK_DIR}/keys/asterisk.key
dtls_ca_file={ASTERISK_DIR}/keys/ca.crt
ice_support=yes
use_avpf=yes
rtcp_mux=yes
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes
media_use_received_transport=yes
identify_by=username
"""

    with open(f"{ASTERISK_DIR}/pjsip.conf", "w") as f:
        f.write(pjsip_content)

print("✅ Provisioning Complete.")

