[intercom-logic]
; Leg 1: The App User (700) triggers the call
exten => 700,1,NoOp(App user triggering Aiphone)
 same => n,Set(CALLERID(all)="OneDoor" <700>)
 same => n,Originate(Local/call-aiphone@intercom-logic,exten,intercom-logic,701,1,30,a(f(700)))
 same => n,ConfBridge(intercom_bridge,,app_user)
 same => n,Hangup()

; Leg 2: The actual SIP call to the Aiphone
exten => call-aiphone,1,NoOp(Setting Headers for Aiphone)
 same => n,Set(CALLERID(all)="OneDoor App" <700>)
 same => n,Dial(PJSIP/105)
 same => n,Hangup()

; Leg 3: Connecting the Aiphone to the Bridge
exten => 701,1,NoOp(Aiphone connected)
 same => n,Answer()
 same => n,ConfBridge(intercom_bridge,,aiphone)
 same => n,Hangup()
